import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@pontual/db'

// All templates use a dynamic URL button pointing to /entrar?t={token}&r=/portal/{slug}/os/{osId}
// The {{N}} variable is the magic-link token generated by the backend at send time.
// The URL portal domain is the production portal for PontualTech.
const PORTAL_BASE = 'https://portal.pontualtech.com.br/portal/pontualtech'

// Meta templates: each component (BODY, BUTTON) has its own independent variable numbering.
// So every URL button always uses {{1}} — it's the first (only) variable of that button.
function magicLinkButton(text: string) {
  return {
    type: 'BUTTONS',
    buttons: [
      {
        type: 'URL',
        text,
        url: `${PORTAL_BASE}/entrar?t={{1}}`,
        example: [`${PORTAL_BASE}/entrar?t=example_token_xxx`],
      },
    ],
  }
}

const TEMPLATES = [
  {
    name: 'pt_coleta_v3',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Coleta agendada' },
      {
        type: 'BODY',
        text: 'PontualTech informa: a coleta do equipamento da OS numero {{1}} foi agendada. Nosso motorista passara no endereco cadastrado em horario comercial. Prepare o equipamento com cabos e fontes.',
        example: { body_text: [['60049']] },
      },
      { type: 'FOOTER', text: 'Toque no botao para acompanhar sua OS' },
      magicLinkButton('Acompanhar OS'),
    ],
  },
  {
    name: 'pt_os_aberta_v3',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Sua OS foi aberta' },
      {
        type: 'BODY',
        text: 'PontualTech informa: sua Ordem de Servico numero {{1}} foi registrada com sucesso. Equipamento: {{2}}. Acompanhe o andamento pelo portal.',
        example: { body_text: [['60049', 'Impressora Epson L3250']] },
      },
      { type: 'FOOTER', text: 'Acesso direto - sem senha' },
      magicLinkButton('Acompanhar OS'),
    ],
  },
  {
    name: 'pontualtech_pronto_v2',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Equipamento pronto' },
      {
        type: 'BODY',
        text: 'PontualTech informa: o equipamento da OS numero {{1}} esta pronto para retirada. Equipamento: {{2}}. Retire na Rua Ouvidor Peleja, 660 - Vila Mariana. Horario: Seg-Qui 8h-18h, Sex 8h-17h.',
        example: { body_text: [['60049', 'Impressora Epson L3250']] },
      },
      { type: 'FOOTER', text: 'Acesso direto - sem senha' },
      magicLinkButton('Ver detalhes'),
    ],
  },
  {
    name: 'pontualtech_orcamento_v2',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Orcamento pronto' },
      {
        type: 'BODY',
        text: 'PontualTech informa: o orcamento da OS numero {{1}} esta pronto. Valor total: {{2}}. Equipamento: {{3}}. Toque no botao para aprovar, recusar ou ver detalhes.',
        example: { body_text: [['60049', 'R$ 635,03', 'Impressora Canon G3111']] },
      },
      { type: 'FOOTER', text: 'Acesso direto - sem senha' },
      magicLinkButton('Aprovar ou Recusar'),
    ],
  },
  {
    name: 'pontualtech_status_os_v2',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Atualizacao da sua OS' },
      {
        type: 'BODY',
        text: 'PontualTech informa: a OS numero {{1}} foi atualizada para o status *{{2}}*. Equipamento: {{3}}. Acompanhe todos os detalhes pelo portal.',
        example: { body_text: [['60049', 'Em Execucao', 'Impressora Epson L3250']] },
      },
      { type: 'FOOTER', text: 'Acesso direto - sem senha' },
      magicLinkButton('Acompanhar OS'),
    ],
  },
  {
    name: 'pt_cobranca_v3',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Cobranca disponivel' },
      {
        type: 'BODY',
        text: 'PontualTech informa: voce tem uma cobranca no valor de {{1}} referente a OS numero {{2}}. Pague de forma rapida e segura pelo link abaixo.',
        example: { body_text: [['R$ 635,03', '60049']] },
      },
      { type: 'FOOTER', text: 'Acesso direto - sem senha' },
      magicLinkButton('Pagar Agora'),
    ],
  },
  {
    name: 'pt_followup_v3',
    language: 'pt_BR',
    category: 'UTILITY',
    components: [
      { type: 'HEADER', format: 'TEXT', text: 'Precisamos da sua resposta' },
      {
        type: 'BODY',
        text: 'PontualTech informa: identificamos que a OS numero {{1}} aguarda sua resposta. Equipamento: {{2}}. Toque no botao para ver os detalhes.',
        example: { body_text: [['60049', 'Impressora Epson L3250']] },
      },
      { type: 'FOOTER', text: 'Acesso direto - sem senha' },
      magicLinkButton('Ver OS'),
    ],
  },
]

export async function POST(req: NextRequest) {
  const key = req.headers.get('x-internal-key')
  const valid = [process.env.CRON_SECRET, process.env.CHATWOOT_WEBHOOK_SECRET].filter(Boolean)
  if (!key || !valid.includes(key)) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { company_id } = await req.json().catch(() => ({}))
  const settings = await prisma.setting.findMany({
    where: { company_id, key: { startsWith: 'whatsapp.cloud.' } },
  })
  const cfg: Record<string, string> = {}
  for (const s of settings) cfg[s.key] = s.value

  const token = cfg['whatsapp.cloud.access_token']
  const wabaId = cfg['whatsapp.cloud.business_account_id']
  if (!token || !wabaId) return NextResponse.json({ error: 'not configured' }, { status: 400 })

  const results: any[] = []
  for (const tmpl of TEMPLATES) {
    try {
      const res = await fetch(`https://graph.facebook.com/v21.0/${wabaId}/message_templates`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(tmpl),
      })
      const data = await res.json()
      results.push({ name: tmpl.name, status: res.status, response: data })
    } catch (e: any) {
      results.push({ name: tmpl.name, error: String(e) })
    }
  }

  return NextResponse.json({ results })
}
