-- ============================================================================
-- Migration 0050_telefonia_f1 — Telefonia Fase 1 (PBX + ramal-ramal)
-- ============================================================================
-- Generated by Prisma. Multi-tenant: companyId em TODAS as tabelas.
-- Affects production: NO existing tables touched. New tables only.
-- Run: npx prisma migrate deploy
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1) Enums
-- ============================================================================
CREATE TYPE "voip_auth_method"      AS ENUM ('IP_BASED', 'USER_SECRET');
CREATE TYPE "voip_extension_status" AS ENUM ('ACTIVE', 'DISABLED', 'PROVISIONING');

-- ============================================================================
-- 2) voip_providers — trunks SIP por empresa
-- ============================================================================
CREATE TABLE "voip_providers" (
  "id"                  UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
  "company_id"          UUID                    NOT NULL REFERENCES "companies"("id") ON DELETE RESTRICT,
  "name"                TEXT                    NOT NULL,
  "host_outbound"       TEXT                    NOT NULL,
  "host_inbound"        TEXT,
  "port"                INTEGER                 NOT NULL DEFAULT 5060,
  "transport"           TEXT                    NOT NULL DEFAULT 'udp',
  "auth_method"         "voip_auth_method"      NOT NULL,
  "username"            TEXT,
  "secret_encrypted"    TEXT,
  "match_ip"            TEXT,
  "codecs"              TEXT[]                  NOT NULL DEFAULT ARRAY['ulaw','alaw']::TEXT[],
  "dtmf_mode"           TEXT                    NOT NULL DEFAULT 'rfc4733',
  "qualify_frequency"   INTEGER                 NOT NULL DEFAULT 60,
  "context_outbound"    TEXT                    NOT NULL DEFAULT 'from-internal',
  "context_inbound"     TEXT                    NOT NULL,
  "is_active"           BOOLEAN                 NOT NULL DEFAULT TRUE,
  "created_at"          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
  "updated_at"          TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
  "deleted_at"          TIMESTAMPTZ,
  "created_by"          UUID,
  "updated_by"          UUID
);
CREATE INDEX "voip_providers_company_id_is_active_idx"
  ON "voip_providers"("company_id","is_active");
CREATE INDEX "voip_providers_company_id_deleted_at_idx"
  ON "voip_providers"("company_id","deleted_at");

-- ============================================================================
-- 3) voip_extensions — ramais SIP
-- ============================================================================
CREATE TABLE "voip_extensions" (
  "id"                  UUID                      PRIMARY KEY DEFAULT gen_random_uuid(),
  "company_id"          UUID                      NOT NULL REFERENCES "companies"("id") ON DELETE RESTRICT,
  "number"              TEXT                      NOT NULL,
  "display_name"        TEXT                      NOT NULL,
  "user_id"             UUID                      REFERENCES "users"("id") ON DELETE SET NULL,
  "secret_encrypted"    TEXT                      NOT NULL,
  "context"             TEXT                      NOT NULL DEFAULT 'from-pontualtech',
  "tenant_tag"          TEXT                      NOT NULL,
  "codecs"              TEXT[]                    NOT NULL DEFAULT ARRAY['ulaw','alaw']::TEXT[],
  "dtmf_mode"           TEXT                      NOT NULL DEFAULT 'rfc4733',
  "max_contacts"        INTEGER                   NOT NULL DEFAULT 2,
  "status"              "voip_extension_status"   NOT NULL DEFAULT 'PROVISIONING',
  "call_limit"          INTEGER,
  "created_at"          TIMESTAMPTZ               NOT NULL DEFAULT NOW(),
  "updated_at"          TIMESTAMPTZ               NOT NULL DEFAULT NOW(),
  "deleted_at"          TIMESTAMPTZ,
  "created_by"          UUID,
  "updated_by"          UUID
);
CREATE UNIQUE INDEX "voip_extensions_company_id_number_key"
  ON "voip_extensions"("company_id","number");
CREATE INDEX "voip_extensions_company_id_status_idx"
  ON "voip_extensions"("company_id","status");
CREATE INDEX "voip_extensions_company_id_user_id_idx"
  ON "voip_extensions"("company_id","user_id");
CREATE INDEX "voip_extensions_company_id_deleted_at_idx"
  ON "voip_extensions"("company_id","deleted_at");

-- ============================================================================
-- 4) voip_inbound_numbers — DIDs
-- ============================================================================
CREATE TABLE "voip_inbound_numbers" (
  "id"                  UUID                NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
  "company_id"          UUID                NOT NULL REFERENCES "companies"("id") ON DELETE RESTRICT,
  "provider_id"         UUID                NOT NULL REFERENCES "voip_providers"("id") ON DELETE RESTRICT,
  "ddd"                 CHAR(2)             NOT NULL,
  "number"              TEXT                NOT NULL,
  "e164"                TEXT                NOT NULL,
  "label"               TEXT                NOT NULL,
  "is_active"           BOOLEAN             NOT NULL DEFAULT TRUE,
  "created_at"          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
  "updated_at"          TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
  "created_by"          UUID
);
CREATE UNIQUE INDEX "voip_inbound_numbers_e164_key"
  ON "voip_inbound_numbers"("e164");
CREATE INDEX "voip_inbound_numbers_company_id_idx"
  ON "voip_inbound_numbers"("company_id");
CREATE INDEX "voip_inbound_numbers_provider_id_idx"
  ON "voip_inbound_numbers"("provider_id");

-- ============================================================================
-- 5) voip_presence
-- ============================================================================
CREATE TABLE "voip_presence" (
  "extension_id"        UUID                PRIMARY KEY REFERENCES "voip_extensions"("id") ON DELETE CASCADE,
  "company_id"          UUID                NOT NULL REFERENCES "companies"("id") ON DELETE RESTRICT,
  "status"              TEXT                NOT NULL DEFAULT 'offline',
  "contact_uri"         TEXT,
  "last_seen_at"        TIMESTAMPTZ,
  "updated_at"          TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);
CREATE INDEX "voip_presence_company_id_status_idx"
  ON "voip_presence"("company_id","status");

-- ============================================================================
-- 6) voip_audit_log
-- ============================================================================
CREATE TABLE "voip_audit_log" (
  "id"                  UUID                PRIMARY KEY DEFAULT gen_random_uuid(),
  "company_id"          UUID                NOT NULL REFERENCES "companies"("id") ON DELETE RESTRICT,
  "user_id"             UUID                REFERENCES "users"("id") ON DELETE SET NULL,
  "action"              TEXT                NOT NULL,
  "entity_type"         TEXT                NOT NULL,
  "entity_id"           UUID,
  "diff"                JSONB,
  "ip_address"          TEXT,
  "user_agent"          TEXT,
  "created_at"          TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);
CREATE INDEX "voip_audit_log_company_id_created_at_idx"
  ON "voip_audit_log"("company_id","created_at" DESC);
CREATE INDEX "voip_audit_log_entity_type_entity_id_idx"
  ON "voip_audit_log"("entity_type","entity_id");

-- ============================================================================
-- 7) RLS — habilita Row Level Security em todas as 5 tabelas
-- ============================================================================
ALTER TABLE "voip_providers"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "voip_extensions"       ENABLE ROW LEVEL SECURITY;
ALTER TABLE "voip_inbound_numbers"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE "voip_presence"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "voip_audit_log"        ENABLE ROW LEVEL SECURITY;

-- Forçar RLS mesmo para owners (defense in depth — anti-pattern B.2)
ALTER TABLE "voip_providers"        FORCE ROW LEVEL SECURITY;
ALTER TABLE "voip_extensions"       FORCE ROW LEVEL SECURITY;
ALTER TABLE "voip_inbound_numbers"  FORCE ROW LEVEL SECURITY;
ALTER TABLE "voip_presence"         FORCE ROW LEVEL SECURITY;
ALTER TABLE "voip_audit_log"        FORCE ROW LEVEL SECURITY;

-- ============================================================================
-- 8) Policies — tenant isolation (cada user só vê dados da empresa dele)
-- ============================================================================
-- Padrão: company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())

CREATE POLICY "voip_providers_tenant"
  ON "voip_providers"
  FOR ALL
  USING (
    "company_id" IN (
      SELECT "company_id" FROM "company_users" WHERE "user_id" = auth.uid()
    )
  );

CREATE POLICY "voip_extensions_tenant"
  ON "voip_extensions"
  FOR ALL
  USING (
    "company_id" IN (
      SELECT "company_id" FROM "company_users" WHERE "user_id" = auth.uid()
    )
  );

CREATE POLICY "voip_inbound_numbers_tenant"
  ON "voip_inbound_numbers"
  FOR ALL
  USING (
    "company_id" IN (
      SELECT "company_id" FROM "company_users" WHERE "user_id" = auth.uid()
    )
  );

CREATE POLICY "voip_presence_tenant"
  ON "voip_presence"
  FOR ALL
  USING (
    "company_id" IN (
      SELECT "company_id" FROM "company_users" WHERE "user_id" = auth.uid()
    )
  );

CREATE POLICY "voip_audit_log_tenant"
  ON "voip_audit_log"
  FOR SELECT
  USING (
    "company_id" IN (
      SELECT "company_id" FROM "company_users" WHERE "user_id" = auth.uid()
    )
  );

-- ============================================================================
-- 9) Policies — super admin bypass (Karlão / role superadmin)
-- ============================================================================
-- Função is_super_admin() já existe no banco (run 8). Reutiliza.

CREATE POLICY "voip_providers_superadmin"
  ON "voip_providers"        FOR ALL USING (is_super_admin());

CREATE POLICY "voip_extensions_superadmin"
  ON "voip_extensions"       FOR ALL USING (is_super_admin());

CREATE POLICY "voip_inbound_numbers_superadmin"
  ON "voip_inbound_numbers"  FOR ALL USING (is_super_admin());

CREATE POLICY "voip_presence_superadmin"
  ON "voip_presence"         FOR ALL USING (is_super_admin());

CREATE POLICY "voip_audit_log_superadmin"
  ON "voip_audit_log"        FOR SELECT USING (is_super_admin());

-- ============================================================================
-- 10) Service-role bypass (server-side service key tem acesso total)
-- ============================================================================
-- Padrão do projeto: service_role bypass para server-side via Prisma direct connection.
-- Não criamos policy explícita pois o service_role já tem BYPASSRLS no banco.

COMMIT;